name: Build
'on':
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: 0eb7723e-8146-4fba-a8a0-c7bf88e1d38b
          SONAR_TOKEN: 6c6b2469c3347bcc5a90cd7dbec5c8ce8a816eb6
          args: >-
            -Dsonar.projectKey=examly-test_0eb7723e-8146-4fba-a8a0-c7bf88e1d38b
            -Dsonar.organization=examly-test
            -Dsonar.sources=aspnet-core-angular/,mvc-angularjs/src
            -Dsonar.verbose=true
